# Generated by Django 5.0.6 on 2024-06-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ScrapeRecord",
        ),
    ]
