# Generated by Django 5.0.6 on 2024-06-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapersession",
            name="treshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Occasion treshold",
            ),
        ),
    ]
