# Generated by Django 5.0.6 on 2024-08-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0006_scrapersession_artificial_page_stop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scrapersession",
            name="treshold",
        ),
        migrations.AddField(
            model_name="scrapersession",
            name="threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="Special offer threshold",
            ),
        ),
    ]
