# Generated by Django 5.0.6 on 2024-05-20 12:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField(verbose_name="Title")),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Price",
                    ),
                ),
                ("subpage", models.URLField(unique=True, verbose_name="Subpage")),
                ("rooms", models.IntegerField(verbose_name="Rooms")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Area"
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        choices=[
                            ("poddasze", "Attic"),
                            ("suterena", "Basecment"),
                            ("parter", "Ground floor"),
                            ("10+", "Upper than 10"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        max_length=20,
                        verbose_name="Floor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartment",
                "verbose_name_plural": "Apartments",
            },
        ),
    ]
