# Generated by Django 5.0.6 on 2024-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.PositiveSmallIntegerField(verbose_name="Rooms"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
