# Generated by Django 5.0.6 on 2024-05-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0002_alter_apartment_address_alter_apartment_rooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="subpage",
            field=models.URLField(editable=False, unique=True, verbose_name="Subpage"),
        ),
    ]
