# Generated by Django 5.0.6 on 2024-05-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0004_apartmentdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Area",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="floor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("poddasze", "Attic"),
                    ("suterena", "Basecment"),
                    ("parter", "Ground floor"),
                    ("10+", "Upper than 10"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10", "10"),
                ],
                max_length=20,
                null=True,
                verbose_name="Floor",
            ),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="rooms",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Rooms"
            ),
        ),
    ]
