# Generated by Django 5.0.6 on 2024-06-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0006_alter_apartmentdetails_energy_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartment",
            name="was_deleted",
            field=models.BooleanField(default=False, verbose_name="Was Deleted"),
        ),
    ]
