# Generated by Django 5.0.6 on 2024-06-18 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0008_apartment_status_apartmentdetails_exact_floor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="was_deleted",
        ),
        migrations.AlterField(
            model_name="apartmentdetails",
            name="apartment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="apartments.apartment",
                verbose_name="Apartment",
            ),
        ),
    ]
