# Generated by Django 5.0.6 on 2024-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0009_remove_apartment_was_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentdetails",
            name="finishing_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("do wykończenia", "To finish"),
                    ("do zamieszkania", "To live"),
                    ("do remontu", "To renovate"),
                ],
                max_length=64,
                null=True,
                verbose_name="Finishing Condition",
            ),
        ),
        migrations.AlterField(
            model_name="apartmentdetails",
            name="market",
            field=models.CharField(
                blank=True,
                choices=[("pierwotny", "Primary"), ("wtórny", "Secondary")],
                max_length=64,
                null=True,
                verbose_name="Market",
            ),
        ),
    ]
