# Generated by Django 5.0.6 on 2024-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartments", "0011_apartment_estimated_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING_FOR_DETAILS", "Awaiting details"),
                    ("SYNCHRONIZED", "Synchronized"),
                    ("VALUATED", "VALUATED"),
                    ("DELETED", "deleted"),
                ],
                default="WAITING_FOR_DETAILS",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
