# Generated by Django 5.0.6 on 2024-06-18 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("result", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
