# Generated by Django 5.0.6 on 2024-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="celeryresult",
            name="task_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
