# Generated by Django 5.0.6 on 2024-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_celeryresult_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="celeryresult",
            name="arguments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="celeryresult",
            name="errors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="celeryresult",
            name="is_success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="celeryresult",
            name="logs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
