# Generated by Django 5.0.6 on 2024-06-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_author_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
